# Call Library & Import File

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_excel('/content/DailySales.xlsx')

#Data Exploration & Cleaning

In [ ]:
df.shape

(13324, 34)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13324 entries, 0 to 13323
Data columns (total 37 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              13323 non-null  datetime64[ns]
 1   Title             13233 non-null  object
 2   Account Title     13323 non-null  object
 3   Market Place      13323 non-null  object
 4   SKU               13323 non-null  object
 5   FNSKU             13323 non-null  object
 6   ASIN              13284 non-null  object
 7   Parent ASIN       2130 non-null   object
 8   Is Parent         13323 non-null  float64
 9   Internal Name     0 non-null      float64
 10  Brand             13233 non-null  object
 11  Product Group     0 non-null      float64
 12  Taxes             13323 non-null  float64
 13  Orders            13323 non-null  float64
 14  Units             13323 non-null  float64
 15  Refunded          13323 non-null  float64
 16  Refund %          13323 non-null  float64
 17  Unit Session %    13323 non-null  float64
 18  Promo Units       13323 non-null  float64
 19  Organic Units     13323 non-null  float64
 20  Per Unit Revenue  11996 non-null  float64
 21  Revenue           13324 non-null  float64
 22  COGS              13323 non-null  float64
 23  FBA Fees          13323 non-null  float64
 24  Promo Amount      13323 non-null  float64
 25  Sessions          13323 non-null  float64
 26  Page Views        13323 non-null  float64
 27  Impressions       13323 non-null  float64
 28  Clicks            13323 non-null  float64
 29  PPC Orders        13323 non-null  float64
 30  PPC Sales         13323 non-null  float64
 31  PPC Cost          13323 non-null  float64
 32  PPC Conv          13323 non-null  float64
 33  OOE               13323 non-null  float64
 34  Net Profit        13323 non-null  float64
 35  Net Margin        13323 non-null  float64
 36  Net ROI           13323 non-null  float64
dtypes: datetime64[ns](1), float64(28), object(8)
memory usage: 3.8+ MB

In [ ]:
# df['Product Group'].isnull().nunique()

#Drop ( Product Group ) Column -- Null column
df = df.drop('Product Group' , axis=1)

In [ ]:
#Drop ( Internal Name ) Column -- Null column
df = df.drop('Internal Name' ,  axis=1)

In [ ]:
#Drop ( Parent ASIN ) Column -- Null column
df = df.drop('Parent ASIN' , axis=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13324 entries, 0 to 13323
Data columns (total 35 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              13323 non-null  datetime64[ns]
 1   Title             13233 non-null  object
 2   Account Title     13323 non-null  object
 3   Market Place      13323 non-null  object
 4   SKU               13323 non-null  object
 5   FNSKU             13323 non-null  object
 6   ASIN              13284 non-null  object
 7   Parent ASIN       2130 non-null   object
 8   Is Parent         13323 non-null  float64
 9   Brand             13233 non-null  object
 10  Taxes             13323 non-null  float64
 11  Orders            13323 non-null  float64
 12  Units             13323 non-null  float64
 13  Refunded          13323 non-null  float64
 14  Refund %          13323 non-null  float64
 15  Unit Session %    13323 non-null  float64
 16  Promo Units       13323 non-null  float64
 17  Organic Units     13323 non-null  float64
 18  Per Unit Revenue  11996 non-null  float64
 19  Revenue           13324 non-null  float64
 20  COGS              13323 non-null  float64
 21  FBA Fees          13323 non-null  float64
 22  Promo Amount      13323 non-null  float64
 23  Sessions          13323 non-null  float64
 24  Page Views        13323 non-null  float64
 25  Impressions       13323 non-null  float64
 26  Clicks            13323 non-null  float64
 27  PPC Orders        13323 non-null  float64
 28  PPC Sales         13323 non-null  float64
 29  PPC Cost          13323 non-null  float64
 30  PPC Conv          13323 non-null  float64
 31  OOE               13323 non-null  float64
 32  Net Profit        13323 non-null  float64
 33  Net Margin        13323 non-null  float64
 34  Net ROI           13323 non-null  float64
dtypes: datetime64[ns](1), float64(26), object(8)
memory usage: 3.6+ MB

In [ ]:
df

,Date,Title,Account Title,Market Place,SKU,FNSKU,ASIN,Parent ASIN,Is Parent,Brand,Taxes,Orders,Units,Refunded,Refund %,Unit Session %,Promo Units,Organic Units,Per Unit Revenue,Revenue,COGS,FBA Fees,Promo Amount,Sessions,Page Views,Impressions,Clicks,PPC Orders,PPC Sales,PPC Cost,PPC Conv,OOE,Net Profit,Net Margin,Net ROI
0,2020-10-01,High Absorption Magnesium Citrate Supplements ...,[ UK ] Aava,UK,UK_Aava_Magnesium_400mg_120_05,X000JJIQ79,B01GU9QLZC,NaN,0.0,AAVALABS,-50.34,17.0,17.0,0.0,0.0,0.0,0.0,17.0,17.88,303.94,-88.63,-90.50,-5.13,0.0,0.0,3423.0,13.0,2.0,29.36,-13.06,0.1538,0.0,56.28,0.1852,0.3142
1,2020-10-02,High Absorption Magnesium Citrate Supplements ...,[ UK ] Aava,UK,UK_Aava_Magnesium_400mg_120_05,X000JJIQ79,B01GU9QLZC,NaN,0.0,AAVALABS,-58.89,20.0,20.0,0.0,0.0,0.0,0.0,20.0,17.63,352.70,-104.33,-104.23,-6.18,0.0,0.0,2786.0,7.0,0.0,0.00,-7.33,0.0000,0.0,71.73,0.2034,0.3439
2,2020-10-03,High Absorption Magnesium Citrate Supplements ...,[ UK ] Aava,UK,UK_Aava_Magnesium_400mg_120_05,X000JJIQ79,B01GU9QLZC,NaN,0.0,AAVALABS,-72.41,18.0,24.0,0.0,0.0,0.0,0.0,24.0,18.45,442.79,-125.20,-128.88,-48.77,0.0,0.0,2927.0,7.0,1.0,14.69,-6.15,0.1429,0.0,61.37,0.1386,0.2416
3,2020-10-04,High Absorption Magnesium Citrate Supplements ...,[ UK ] Aava,UK,UK_Aava_Magnesium_400mg_120_05,X000JJIQ79,B01GU9QLZC,NaN,0.0,AAVALABS,-41.43,13.0,14.0,0.0,0.0,0.0,0.0,14.0,17.93,251.01,-73.03,-74.12,-6.42,0.0,0.0,3584.0,16.0,2.0,44.07,-16.51,0.1250,0.0,39.49,0.1573,0.2684
4,2020-10-05,High Absorption Magnesium Citrate Supplements ...,[ UK ] Aava,UK,UK_Aava_Magnesium_400mg_120_05,X000JJIQ79,B01GU9QLZC,NaN,0.0,AAVALABS,-47.04,16.0,16.0,0.0,0.0,0.0,0.0,16.0,17.69,282.96,-83.34,-83.49,-4.76,0.0,0.0,4329.0,7.0,0.0,0.00,-4.47,0.0000,0.0,59.86,0.2116,0.3588
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13319,2021-03-28,Gélules biodisponibles du complexe de curcumin...,[ FR ] Aava,FR,FR_Aava_Turmeric_1400mg_180_01,X000UL0561,B07CXYM3H5,NaN,0.0,AAVALABS,-3.88,3.0,4.0,0.0,0.0,0.0,0.0,4.0,18.69,74.76,-28.82,-27.17,-0.93,0.0,0.0,37.0,0.0,0.0,0.00,0.00,0.0000,0.0,13.96,0.1867,0.2493
13320,2021-03-29,Gélules biodisponibles du complexe de curcumin...,[ FR ] Aava,FR,FR_Aava_Turmeric_1400mg_180_01,X000UL0561,B07CXYM3H5,NaN,0.0,AAVALABS,-7.16,6.0,6.0,0.0,0.0,0.0,0.0,6.0,22.82,136.93,-43.23,-48.20,0.00,0.0,0.0,16.0,0.0,0.0,0.00,0.00,0.0000,0.0,38.34,0.2800,0.4193
13321,2021-03-30,Gélules biodisponibles du complexe de curcumin...,[ FR ] Aava,FR,FR_Aava_Turmeric_1400mg_180_01,X000UL0561,B07CXYM3H5,NaN,0.0,AAVALABS,-9.20,6.0,8.0,0.0,0.0,0.0,0.0,8.0,22.61,180.91,-57.64,-58.55,-6.09,0.0,0.0,57.0,1.0,2.0,36.94,-0.71,2.0000,0.0,48.72,0.2693,0.4193
13322,2021-03-31,Gélules biodisponibles du complexe de curcumin...,[ FR ] Aava,FR,FR_Aava_Turmeric_1400mg_180_01,X000UL0561,B07CXYM3H5,NaN,0.0,AAVALABS,-3.45,3.0,3.0,0.0,0.0,0.0,0.0,3.0,21.99,65.97,-21.62,-22.02,0.00,0.0,0.0,115.0,0.0,0.0,0.00,0.00,0.0000,0.0,18.89,0.2863,0.4328
13323,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1151257.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.isnull().sum()

Date                    1
Title                  91
Account Title           1
Market Place            1
SKU                     1
FNSKU                   1
ASIN                   40
Parent ASIN         11194
Is Parent               1
Brand                  91
Taxes                   1
Orders                  1
Units                   1
Refunded                1
Refund %                1
Unit Session %          1
Promo Units             1
Organic Units           1
Per Unit Revenue     1328
Revenue                 0
COGS                    1
FBA Fees                1
Promo Amount            1
Sessions                1
Page Views              1
Impressions             1
Clicks                  1
PPC Orders              1
PPC Sales               1
PPC Cost                1
PPC Conv                1
OOE                     1
Net Profit              1
Net Margin              1
Net ROI                 1
dtype: int64

In [ ]:
df['Per Unit Revenue'].value_counts()

Per Unit Revenue
19.99    889
20.99    432
22.99    344
21.99    258
16.99    212
        ...
15.05      1
13.11      1
15.94      1
14.59      1
10.16      1
Name: count, Length: 1483, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13324 entries, 0 to 13323
Data columns (total 35 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              13323 non-null  datetime64[ns]
 1   Title             13233 non-null  object
 2   Account Title     13323 non-null  object
 3   Market Place      13323 non-null  object
 4   SKU               13323 non-null  object
 5   FNSKU             13323 non-null  object
 6   ASIN              13284 non-null  object
 7   Parent ASIN       2130 non-null   object
 8   Is Parent         13323 non-null  float64
 9   Brand             13233 non-null  object
 10  Taxes             13323 non-null  float64
 11  Orders            13323 non-null  float64
 12  Units             13323 non-null  float64
 13  Refunded          13323 non-null  float64
 14  Refund %          13323 non-null  float64
 15  Unit Session %    13323 non-null  float64
 16  Promo Units       13323 non-null  float64
 17  Organic Units     13323 non-null  float64
 18  Per Unit Revenue  11996 non-null  float64
 19  Revenue           13324 non-null  float64
 20  COGS              13323 non-null  float64
 21  FBA Fees          13323 non-null  float64
 22  Promo Amount      13323 non-null  float64
 23  Sessions          13323 non-null  float64
 24  Page Views        13323 non-null  float64
 25  Impressions       13323 non-null  float64
 26  Clicks            13323 non-null  float64
 27  PPC Orders        13323 non-null  float64
 28  PPC Sales         13323 non-null  float64
 29  PPC Cost          13323 non-null  float64
 30  PPC Conv          13323 non-null  float64
 31  OOE               13323 non-null  float64
 32  Net Profit        13323 non-null  float64
 33  Net Margin        13323 non-null  float64
 34  Net ROI           13323 non-null  float64
dtypes: datetime64[ns](1), float64(26), object(8)
memory usage: 3.6+ MB

In [ ]:
df['Parent ASIN'].isnull().sum()

np.int64(11194)

In [ ]:
df['ASIN'].unique()

array(['B01GU9QLZC', 'B01GU9P0M2', 'B01GU8L68A', 'B07CXYM3H5',
       'B07CZ1P4BM', 'B07F6FJPQJ', 'B07F838ZVV', 'B07CGSXNH4',
       'B07CXYWF66', 'B07CY19DMQ', 'B07GBFMRMR', 'B07GH48YC6',
       'B07GWNXM53', 'B07GH48YD7', 'B07H36MLFB', 'B07HDCS5R1',
       'B07JVPP2XF', 'B07JBP4X9H', 'B07JBC3GWM', 'B07JCGX3CG',
       'B07KB28H4B', 'B07KPP2V98', 'B07CXWG8Z9', 'B07MW9GTSR',
       'B07NXST2Q9', 'B07NXTVSNR', 'B07NYQ3X5R', 'B07P1T8J4P',
       'B07P5833LZ', 'B07P57TCTL', 'B07PH3WCF3', 'B07PH2191C',
       'B07PH3X8RV', 'B07PT8N8GP', 'B07QXPNGQJ', 'B01BSQQBZW',
       'B01M3U8Y9M', 'B07R5ZHBRJ', nan, 'B07RBWFM1T', 'B07WW7DRQQ',
       'B07WV3QJLD', 'B07YWZ86BM', 'B07Z9FS699', 'B07Z9FM321',
       'B082J2ZH9Z', 'B082MMPBNG', 'B083V4MH39', 'B08475TXQ6',
       'B0847RMCL2', 'B084ZLR2D9', 'B084ZMSZ6J', 'B08576VCZW',
       'B01H1WPOF0', 'B08HZGF7B4', 'B08J19XXFL', 'B08K9BNFS7',
       'B08K9D3BJL', 'B08K99KS8Z', 'B08KDT2NB5', 'B08QJP9DZH',
       'B08SMN3817', 'B01CSNQ3EI', 'B01J3Y57UQ', 'B01I5DF1U2',
       'B01N9JNOQ6', 'B06XXMJ32C', 'B06XXMKJKC', 'B06XHNSGZB',
       'B06XH8S2N8', 'B0765SRGZJ', 'B0784R5277', 'B07CN5VF7S',
       'B07CNJFMQV'], dtype=object)

In [ ]:
df['Parent ASIN'].value_counts()

Parent ASIN
B08P3HP9MH    417
B08Q4FNGYQ    417
B092ZXC3XB    376
B08SWNCMFM    332
B0913DH4Y1    329
B0929721G7    259
Name: count, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13324 entries, 0 to 13323
Data columns (total 34 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              13323 non-null  datetime64[ns]
 1   Title             13233 non-null  object
 2   Account Title     13323 non-null  object
 3   Market Place      13323 non-null  object
 4   SKU               13323 non-null  object
 5   FNSKU             13323 non-null  object
 6   ASIN              13284 non-null  object
 7   Is Parent         13323 non-null  float64
 8   Brand             13233 non-null  object
 9   Taxes             13323 non-null  float64
 10  Orders            13323 non-null  float64
 11  Units             13323 non-null  float64
 12  Refunded          13323 non-null  float64
 13  Refund %          13323 non-null  float64
 14  Unit Session %    13323 non-null  float64
 15  Promo Units       13323 non-null  float64
 16  Organic Units     13323 non-null  float64
 17  Per Unit Revenue  11996 non-null  float64
 18  Revenue           13324 non-null  float64
 19  COGS              13323 non-null  float64
 20  FBA Fees          13323 non-null  float64
 21  Promo Amount      13323 non-null  float64
 22  Sessions          13323 non-null  float64
 23  Page Views        13323 non-null  float64
 24  Impressions       13323 non-null  float64
 25  Clicks            13323 non-null  float64
 26  PPC Orders        13323 non-null  float64
 27  PPC Sales         13323 non-null  float64
 28  PPC Cost          13323 non-null  float64
 29  PPC Conv          13323 non-null  float64
 30  OOE               13323 non-null  float64
 31  Net Profit        13323 non-null  float64
 32  Net Margin        13323 non-null  float64
 33  Net ROI           13323 non-null  float64
dtypes: datetime64[ns](1), float64(26), object(7)
memory usage: 3.5+ MB

In [ ]:
df[['PPC Orders'	, 'PPC Sales' , 	'PPC Cost' , 	'PPC Conv' , 	'OOE' ,	'Net Profit' , 	'Net Margin' ,	'Net ROI']].describe()

,PPC Orders,PPC Sales,PPC Cost,PPC Conv,OOE,Net Profit,Net Margin,Net ROI
count,13323.000000,13323.000000,13323.000000,13323.000000,13323.0,13323.000000,1.332300e+04,13323.000000
mean,2.331757,51.895073,-15.246775,0.144013,0.0,61.224216,2.414762e+11,0.294288
std,4.106758,94.217849,26.139957,0.258420,0.0,110.080049,1.278643e+14,0.308586
min,0.000000,0.000000,-1064.850000,0.000000,0.0,-486.310000,-8.702340e+15,-2.940700
25%,0.000000,0.000000,-17.230000,0.000000,0.0,5.350000,7.945000e-02,0.115350
50%,1.000000,18.170000,-6.330000,0.076900,0.0,24.960000,1.903000e-01,0.291900
75%,3.000000,63.610000,-1.140000,0.200000,0.0,65.095000,2.651000e-01,0.439600
max,135.000000,2875.440000,0.000000,6.000000,0.0,2342.190000,1.191953e+16,2.695400

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13324 entries, 0 to 13323
Data columns (total 34 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              13323 non-null  datetime64[ns]
 1   Title             13233 non-null  object
 2   Account Title     13323 non-null  object
 3   Market Place      13323 non-null  object
 4   SKU               13323 non-null  object
 5   FNSKU             13323 non-null  object
 6   ASIN              13284 non-null  object
 7   Is Parent         13323 non-null  float64
 8   Brand             13233 non-null  object
 9   Taxes             13323 non-null  float64
 10  Orders            13323 non-null  float64
 11  Units             13323 non-null  float64
 12  Refunded          13323 non-null  float64
 13  Refund %          13323 non-null  float64
 14  Unit Session %    13323 non-null  float64
 15  Promo Units       13323 non-null  float64
 16  Organic Units     13323 non-null  float64
 17  Per Unit Revenue  11996 non-null  float64
 18  Revenue           13324 non-null  float64
 19  COGS              13323 non-null  float64
 20  FBA Fees          13323 non-null  float64
 21  Promo Amount      13323 non-null  float64
 22  Sessions          13323 non-null  float64
 23  Page Views        13323 non-null  float64
 24  Impressions       13323 non-null  float64
 25  Clicks            13323 non-null  float64
 26  PPC Orders        13323 non-null  float64
 27  PPC Sales         13323 non-null  float64
 28  PPC Cost          13323 non-null  float64
 29  PPC Conv          13323 non-null  float64
 30  OOE               13323 non-null  float64
 31  Net Profit        13323 non-null  float64
 32  Net Margin        13323 non-null  float64
 33  Net ROI           13323 non-null  float64
dtypes: datetime64[ns](1), float64(26), object(7)
memory usage: 3.5+ MB